spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: exampleDb

server:
  port: 9898
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true